### ISSUE TITLE
Prevent cgstats from updating Flask-SQLAlchemy when updating PROD

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/cgstats#16]
When installing the latest version of cgstats in PROD on Rasta, cg broke because Flask-SQLAlchemy was updated to version 2.3.2, it should be locked to version 2.1

**Comment by ingkebil** [comment]
See the following for a suggested permanent fix: https://robots.thoughtbot.com/how-to-manage-your-python-projects-with-pipenv

**Comment by patrikgrenfeldt** [comment]
implemented in #19

**Comment by emiliaol** [comment]
So this card should be archived?

**Comment by barrystokman** [comment]
Yes, please do so in Zube.
