### ISSUE TITLE
3.5 demultiplexing added to cgstats

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/cgstats#20]
As a LIMS developer I want the read information from the iSeq runs to be available for LIMS so that I can us that information for calculations in LIMS and the lab personnel can stop doing manual calculations -> reduced risk of mistakes

Problem: iSeq demux data is not stored anywhere so LIMS can't access it and process it. iSeq is only used for QC purposes to make pooling more even.

Suggested solution:

* `cgstats add -m iSeq` would add the stats from demultiplexing to the database. 
* I think the structure is the same as for the novaseq demux. 
* Example/test data can be found on thalamus here: /home/hiseq.clinical/iSeq/demux
* Decide on either Path 1 or Path 2: **Path 2!**

~~Path 1:~~
~~* A new cgstats db is created for the iSeq data (as these samples will also be run on NovaSeq/Hiseq~~ ~~2500 and the iSeq data should not be added to the total reads of a production sample).~~
~~* For MB: Change bcl2fastq,py EPP to make use of two cgstats dbs~~

path 2:
* The iSeq data is currently excluded from entering statusdb
~~* For MB: Change bcl2fast.py EPP to exclude iSeq data from non-iSeq workflows~~ Is handled through flowcell ID in LIMS.
* add new machine to column in flowcell table in cgstats
* automatically add the stats for the demultiplexing
* update 1060 raw data delivery

Dependencies:
- https://github.com/Clinical-Genomics/cg/blob/master/cg/apps/stats.py -> iSeq is currently excluded
- https://github.com/Clinical-Genomics/clinical_EPPs/blob/master/EPPs/bcl2fastq.py -> iSeq is currently 
  not excluded, but should be for non iSeq workflows.
- Clinical-Genomics/demultiplexing#89 depends on this US.

Tolerances:
* Can be added manually via CLI
* documentation can be handled later

Questions:
1. Q: Does it reap any benefit to include the reads and fastq files to the analysis?
    A: Only reads, no fastq.
1. Q: How would MB exclude the iSeq reads for the other workflows?
    A: Managed on flowcell and workflow level. No action needed.
1. Q: Write method for demuliplexing: is this documentation or implementation?
    A: Implementation. @Clinical-Genomics/team-name Where?
    A:

**Comment by patrikgrenfeldt** [comment]
change iSeq to iseq

**Comment by patrikgrenfeldt** [comment]
resolved by #21
