### ISSUE TITLE
add sequencing date to flowcell/analysis sample

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/cgstats#4]
or can we get this by linking tables @ingkebil?

**Comment by ingkebil** [comment]
There is a `rundate` in `datasource` that refers to the sequencing date. So yes :)

flowcell join demux join datasource.
sample join unaligned join demux join datasource.

**Comment by robinandeer** [comment]
I'll try it out

**Comment by patrikgrenfeldt** [comment]
Closing old issue since it doesn't specify who wants it or what the benefit is
